var N = null;var sourcesIndex = {};
sourcesIndex["elf"] = {"name":"","dirs":[{"name":"section","files":["sh_type.rs"]}],"files":["header.rs","lib.rs","section.rs"]};
sourcesIndex["elf_proc"] = {"name":"","files":["ehdr.rs","lib.rs","metadata.rs","shdr.rs"]};
sourcesIndex["elface"] = {"name":"","files":["lib.rs"]};
sourcesIndex["layout"] = {"name":"","files":["lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["readelf"] = {"name":"","files":["elf32.rs","main.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","gen_helper.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
